# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/VivadoProjects/lab4_1/lab4_1.srcs/sources_1/ip/c_addsub_0_1/c_addsub_0.xci
# IP: The module: 'c_addsub_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/lab4_1/lab4_1.gen/sources_1/ip/c_addsub_0_1/c_addsub_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/VivadoProjects/lab4_1/lab4_1.srcs/sources_1/ip/c_addsub_0_1/c_addsub_0.xci
# IP: The module: 'c_addsub_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/lab4_1/lab4_1.gen/sources_1/ip/c_addsub_0_1/c_addsub_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
