# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/VivadoProjects/lab4_4/lab4_4.srcs/sources_1/ip/add/add.xci
# IP: The module: 'add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/lab4_4/lab4_4.gen/sources_1/ip/add/add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/VivadoProjects/lab4_4/lab4_4.srcs/sources_1/ip/add/add.xci
# IP: The module: 'add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadoProjects/lab4_4/lab4_4.gen/sources_1/ip/add/add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
